openapi: "3.0.0"
info:
  version: 1.0.0
  title: HomeNet
  description: |
    listings of properties for sale
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /listings:
    get:
      summary: Show all listings
      operationId: listings
      tags:
      - listings
      parameters:
      - name: type
        in: query
        description: filter by query type
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Array of listings
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponsePosts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create one listing
      operationId: createListing
      tags:
      - listings
      requestBody:
        description: the listing to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: The created post
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponsePost"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listings/{postId}:
    put:
      summary: Replace one listing
      operationId: putListing
      tags:
      - listings
      parameters:
      - name: postId
        in: path
        description: post id
        required: true
        schema:
          type: string
      requestBody:
        description: the listing to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        '200':
          description: The replaced listing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponsePost"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Delete a Post
      operationId: deletePost
      tags:
        - listings
      parameters:
      - name: postId
        in: path
        description: post id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The deleted post
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponsePost"
        '204':
          description: No change (nothing was deleted)
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    Post:
      type: object
      properties:
        type:
          type: string
        price:
          type: integer
        monthlyfee:
          type: integer
        active:
          type: boolean
        location:
          type: object
          properties:
            city:
              type: string
            street:
              type: string
            number:
              type: integer
            municipality:
              type: string
            country:
              type: string
            lat:
              type: integer
            lon:
              type: integer
    ResponsePost:
      allOf:
      - $ref: "#/components/schemas/Post"
      - properties:
          id:
            type: integer
          _id:
            type: string
            format: uuid
    ResponsePosts:
      type: array
      items:
        $ref: "#/components/schemas/ResponsePost"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
